Update adding-assets.md
electron-react-boilerplate/site pull request #127
Opened 2020-08-23 06:03 UTC by jooohhn

Update docs on adding assets to cover non-Webpack/runtime assets. Related to https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2526

Closes #132

2020-09-19 00:29 UTC, amilajack requested changes

2020-09-19 00:29 UTC, amilajack commented on docs/adding-assets.md
> +```js
Still needs link

2020-09-21 05:57 UTC, jooohhn commented on docs/adding-assets.md
> +```js
Added it here: https://github.com/electron-react-boilerplate/site/pull/127/files#diff-e09f79ffe9a84bf4f1f19679ba6a687aR56

2020-10-11 01:59 UTC, amilajack approved these changes

2020-10-11 02:00 UTC, jooohhn commented
@TODO make sure it's working in packaged bundle

2020-10-11 02:01 UTC, amilajack approved these changes

2020-10-11 02:01 UTC, merged